apiVersion: v1
kind: Service
metadata:
  name: {{ include "time-exporter.fullname" . }}
  labels:
    {{- include "time-exporter.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{ . |toYaml |indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "time-exporter.selectorLabels" . | nindent 4 }}
