---
version: 2.1

orbs:
  prometheus: prometheus/prometheus@0.11.0

executors:
  # Whenever the Go version is updated here, .promu.yml and .promu-cgo.yml
  # should also be updated.
  golang:
    docker:
      - image: circleci/golang:1.16

jobs:
  test:
    executor: golang

    steps:
      - prometheus/setup_environment
      - run: go mod download
      - run: make build
      - prometheus/store_artifact:
          file: time_exporter

  codespell:
    docker:
      - image: circleci/python

    steps:
      - checkout
      - run: sudo pip install codespell
      - run: codespell --skip=".git,./vendor,ttar,go.mod,go.sum,*pem,./collector/fixtures" -L uint,packages\',uptodate

  build:
    machine:
      image: ubuntu-2004:202101-01

    parallelism: 3

    steps:
      - prometheus/setup_environment
      - run: docker run --privileged linuxkit/binfmt:v0.8
      - run: promu crossbuild -v --parallelism $CIRCLE_NODE_TOTAL --parallelism-thread $CIRCLE_NODE_INDEX
      - run: promu --config .promu-cgo.yml crossbuild -v --parallelism $CIRCLE_NODE_TOTAL --parallelism-thread $CIRCLE_NODE_INDEX
      - persist_to_workspace:
          root: .
          paths:
            - .build
      - store_artifacts:
          path: .build
          destination: /build

  test_docker:
    machine:
      image: ubuntu-2004:202101-01

    environment:
      DOCKER_TEST_IMAGE_NAME: quay.io/prometheus/golang-builder:1.16-base
      REPO_PATH: github.com/prometheus/time_exporter

    steps:
      - prometheus/setup_environment
      - attach_workspace:
          at: .
      - run:
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              make docker DOCKER_IMAGE_TAG=$CIRCLE_TAG
            else
              make docker
            fi
      - run: docker images
      - run: docker run --rm -t -v "$(pwd):/app" "${DOCKER_TEST_IMAGE_NAME}" -i "${REPO_PATH}" -T
      - run:
          command: |
            if [ -n "$CIRCLE_TAG" ]; then
              make test-docker DOCKER_IMAGE_TAG=$CIRCLE_TAG
            else
              make test-docker
            fi

  release_docker:
    machine:
      image: ubuntu-2004:202101-01

    steps:
      - prometheus/publish_images:
          container_image_name: "time_exporter"
          login_variable: DOCKER_LOGIN
          password_variable: DOCKER_PASSWORD
          organization: ""
          registry: ""

workflows:
  version: 2
  time_exporter:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/
      - codespell:
          filters:
            tags:
              only: /.*/
      - test_docker:
          requires:
            - test
            - build
          filters:
            tags:
              only: /.*/
      - release_docker:
          context: org-context
          requires:
            - test
            - build
          filters:
            branches:
              only: master