---
version: 2.1

orbs:
  go: circleci/go@1.6.0

executors:
  # Whenever the Go version is updated here, .promu.yml and .promu-cgo.yml
  # should also be updated.
  golang:
    docker:
      - image: circleci/golang:1.16

jobs:
  test:
    executor: golang

    steps:
      - run: checkout
      - run: make build
      - run: go mod download
      - run: make
#      - prometheus/store_artifact:
#          file: time_exporter

  build:
    machine:
      image: ubuntu-2004:202101-01

    parallelism: 3

    steps:
      - run: checkout
      - run: make
      - run: docker run --privileged linuxkit/binfmt:v0.8
      - run: promu crossbuild -v --parallelism $CIRCLE_NODE_TOTAL --parallelism-thread $CIRCLE_NODE_INDEX
      - run: promu --config .promu-cgo.yml crossbuild -v --parallelism $CIRCLE_NODE_TOTAL --parallelism-thread $CIRCLE_NODE_INDEX
      - persist_to_workspace:
          root: .
          paths:
            - .build
      - store_artifacts:
          path: .build
          destination: /build

workflows:
  version: 2
  time_exporter:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - build:
          filters:
            tags:
              only: /.*/